#
###################################
# Site wide configuration
####################################
#
title: public Object innovate();
email: mndeveci@gmail.com
description: My blog about programming
url: https://www.mndeveci.com/ # the base hostname & protocol for your site
keywords: ["Programming", "Java", "Spring", "Hibernate"]
excerpt_separator: <!--more-->

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Amsterdam
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Mehmet Nuri Deveci
  avatar: avatar-test.png
  job: "Software Enthusiast"
  bio: "A Java Developer who loves learning new stuff. Working in Amsterdam, Netherlands"
  email: #mndeveci@gmail.com
  disqus-shortname:
  twitter: mndeveci #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-16633713-6
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mndeveci #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: mndeveci #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
  500px: mndeveci #username
